# Generated by Django 4.0.1 on 2022-01-11 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('address', models.TextField()),
                ('city', models.TextField()),
                ('zipcode', models.IntegerField()),
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
